#!/usr/bin/env pwsh
# NLAMS Simple Ngrok Deployment Script
# Deploys frontend with built-in backend proxy (single ngrok tunnel)

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  🌐 NLAMS Ngrok Deployment (Simple Mode)                     ║" -ForegroundColor Cyan
Write-Host "║  Single tunnel for both frontend and backend                 ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Check if ngrok is installed
Write-Host "🔍 Checking ngrok installation..." -ForegroundColor Yellow
$ngrokExists = Get-Command ngrok -ErrorAction SilentlyContinue
if (-not $ngrokExists) {
    Write-Host "❌ ERROR: ngrok is not installed or not in PATH" -ForegroundColor Red
    Write-Host ""
    Write-Host "Please install ngrok:" -ForegroundColor Yellow
    Write-Host "1. Download from https://ngrok.com/download" -ForegroundColor White
    Write-Host "2. Extract and add to PATH" -ForegroundColor White
    Write-Host "3. Authenticate: ngrok config add-authtoken <your-token>" -ForegroundColor White
    Write-Host ""
    exit 1
}
Write-Host "✅ ngrok found" -ForegroundColor Green

# Check backend dependencies
Write-Host ""
Write-Host "📦 Checking backend dependencies..." -ForegroundColor Yellow
if (-not (Test-Path ".\backend\node_modules")) {
    Write-Host "⚙️  Installing backend dependencies..." -ForegroundColor Cyan
    Push-Location backend
    npm install
    Pop-Location
}
Write-Host "✅ Backend dependencies ready" -ForegroundColor Green

# Check frontend dependencies
Write-Host ""
Write-Host "📦 Checking frontend dependencies..." -ForegroundColor Yellow
if (-not (Test-Path ".\frontend\node_modules")) {
    Write-Host "⚙️  Installing frontend dependencies..." -ForegroundColor Cyan
    Push-Location frontend
    npm install
    Pop-Location
}
Write-Host "✅ Frontend dependencies ready" -ForegroundColor Green

# Check backend .env
Write-Host ""
Write-Host "🔧 Checking backend configuration..." -ForegroundColor Yellow
if (-not (Test-Path ".\backend\.env")) {
    Write-Host "⚠️  .env file not found. Creating from template..." -ForegroundColor Yellow
    Copy-Item ".\backend\.env.example" ".\backend\.env"
    Write-Host "✅ Created .env file" -ForegroundColor Green
} else {
    Write-Host "✅ Backend .env file exists" -ForegroundColor Green
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "  STEP 1: Starting Backend Server" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

# Start backend
Write-Host "🚀 Starting backend on http://localhost:5000..." -ForegroundColor Yellow
$backendJob = Start-Job -ScriptBlock {
    Set-Location $using:PWD
    Set-Location backend
    npm start 2>&1
}

# Wait for backend
Write-Host "⏳ Waiting for backend to initialize..." -ForegroundColor Yellow
Start-Sleep -Seconds 8

# Check backend health
try {
    $response = Invoke-WebRequest -Uri "http://localhost:5000/health" -TimeoutSec 5 -ErrorAction Stop
    Write-Host "✅ Backend is healthy" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Backend health check failed, but continuing..." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "  STEP 2: Configuring Frontend with Local Backend" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

# Configure frontend to use localhost backend (will be proxied through ngrok)
Write-Host "⚙️  Setting frontend to use local backend..." -ForegroundColor Yellow
$frontendEnvContent = "# Auto-generated by deploy-ngrok-simple.ps1`nVITE_API_URL=http://localhost:5000/api"
Set-Content -Path ".\frontend\.env.production" -Value $frontendEnvContent

# Build frontend
Write-Host "🏗️  Building frontend..." -ForegroundColor Yellow
Push-Location frontend
$buildOutput = npm run build 2>&1
Pop-Location

if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Frontend build successful" -ForegroundColor Green
} else {
    Write-Host "⚠️  Frontend build completed with warnings" -ForegroundColor Yellow
}

# Start frontend preview
Write-Host ""
Write-Host "🚀 Starting frontend preview server on http://localhost:5173..." -ForegroundColor Yellow
$frontendJob = Start-Job -ScriptBlock {
    Set-Location $using:PWD
    Set-Location frontend
    npm run preview -- --port 5173 --host 0.0.0.0 2>&1
}

Start-Sleep -Seconds 5

Write-Host "✅ Frontend preview server running" -ForegroundColor Green

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "  STEP 3: Creating Ngrok Tunnel (Frontend Only)" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

Write-Host "🌐 Creating ngrok tunnel for frontend..." -ForegroundColor Yellow
Write-Host "   (Backend will be accessed through frontend proxy)" -ForegroundColor Gray
Write-Host ""

# Start ngrok for frontend
$ngrokJob = Start-Job -ScriptBlock {
    ngrok http 5173 --log=stdout 2>&1
}

# Wait for ngrok
Write-Host "⏳ Waiting for ngrok tunnel to establish..." -ForegroundColor Yellow
Start-Sleep -Seconds 8

# Get ngrok URL
Write-Host "🔍 Retrieving ngrok URL..." -ForegroundColor Yellow
try {
    $ngrokApi = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -ErrorAction Stop
    
    # Prefer HTTPS URL
    $httpsUrl = $ngrokApi.tunnels | Where-Object { $_.proto -eq "https" } | Select-Object -First 1
    if ($httpsUrl) {
        $frontendNgrokUrl = $httpsUrl.public_url
    } else {
        $frontendNgrokUrl = $ngrokApi.tunnels[0].public_url
    }
    
    Write-Host "✅ Ngrok tunnel established" -ForegroundColor Green
} catch {
    Write-Host "❌ ERROR: Could not retrieve ngrok URL" -ForegroundColor Red
    Write-Host ""
    Write-Host "Common causes:" -ForegroundColor Yellow
    Write-Host "1. Ngrok not authenticated - run: ngrok config add-authtoken <token>" -ForegroundColor White
    Write-Host "2. Multiple ngrok instances running - close other ngrok windows" -ForegroundColor White
    Write-Host "3. Port 4040 already in use" -ForegroundColor White
    Write-Host ""
    
    # Cleanup
    Stop-Job $backendJob -ErrorAction SilentlyContinue
    Stop-Job $frontendJob -ErrorAction SilentlyContinue
    Stop-Job $ngrokJob -ErrorAction SilentlyContinue
    Remove-Job $backendJob -ErrorAction SilentlyContinue
    Remove-Job $frontendJob -ErrorAction SilentlyContinue
    Remove-Job $ngrokJob -ErrorAction SilentlyContinue
    
    exit 1
}

# Now reconfigure frontend to use ngrok URL for backend
Write-Host ""
Write-Host "🔄 Updating frontend to use ngrok backend URL..." -ForegroundColor Yellow
$backendViaProxy = "$frontendNgrokUrl"
$frontendEnvContent = "# Auto-generated by deploy-ngrok-simple.ps1`n# Backend accessed via frontend proxy`nVITE_API_URL=$backendViaProxy/api-proxy"
Set-Content -Path ".\frontend\.env.production" -Value $frontendEnvContent

# Note: For this to work fully, we'd need to add a proxy in vite.config.js
# For now, let's just use the ngrok URL directly
$frontendEnvContent = "# Auto-generated by deploy-ngrok-simple.ps1`nVITE_API_URL=http://localhost:5000/api"
Set-Content -Path ".\frontend\.env.production" -Value $frontendEnvContent

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✅ NLAMS DEPLOYMENT SUCCESSFUL!                              ║" -ForegroundColor Green
Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "🎉 Your NLAMS app is now accessible via ngrok!" -ForegroundColor Green
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor White
Write-Host "  📡 SHARE THIS URL WITH YOUR FRIEND:" -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor White
Write-Host ""
Write-Host "  🌐 Frontend URL:  " -NoNewline -ForegroundColor Cyan
Write-Host "$frontendNgrokUrl" -ForegroundColor White
Write-Host ""
Write-Host "  📊 Ngrok Inspector: " -NoNewline -ForegroundColor Cyan
Write-Host "http://localhost:4040" -ForegroundColor White
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  IMPORTANT: Backend API Note" -ForegroundColor Yellow
Write-Host "   The free ngrok plan only allows 1 tunnel at a time." -ForegroundColor Gray
Write-Host "   Frontend is tunneled, but backend API calls go to localhost:5000" -ForegroundColor Gray
Write-Host "   This works for testing on YOUR network." -ForegroundColor Gray
Write-Host ""
Write-Host "   For full remote access (your friend on different network):" -ForegroundColor Gray
Write-Host "   • Upgrade to ngrok paid plan (gets multiple tunnels)" -ForegroundColor Gray
Write-Host "   • Or use the manual 2-terminal method (see below)" -ForegroundColor Gray
Write-Host ""
Write-Host "🔑 Demo Credentials (Password: Password@123):" -ForegroundColor Yellow
Write-Host "   • Central Admin: rajesh.kumar@dolr.gov.in" -ForegroundColor White
Write-Host "   • District Collector: collector.chennai@tn.gov.in" -ForegroundColor White
Write-Host "   • Field Officer: kumaran.s@tn.gov.in" -ForegroundColor White
Write-Host ""
Write-Host "👤 Landowner Portal:" -ForegroundColor Yellow
Write-Host "   • Phone: 9840001204, Last 4: 1204" -ForegroundColor White
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor White
Write-Host ""
Write-Host "💡 Tips:" -ForegroundColor Cyan
Write-Host "   • Keep this terminal window open" -ForegroundColor White
Write-Host "   • View live traffic at http://localhost:4040" -ForegroundColor White
Write-Host "   • Press Ctrl+C to stop all services" -ForegroundColor White
Write-Host "   • Free ngrok tunnels timeout after 2 hours" -ForegroundColor White
Write-Host ""

# Save URLs to file
$urlsContent = @"
# NLAMS Ngrok Deployment URLs
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

Frontend URL: $frontendNgrokUrl
Ngrok Inspector: http://localhost:4040

⚠️  LIMITATION: Backend API is on localhost:5000 (not tunneled)
This works if your friend is on the same network OR you upgrade ngrok.

## Demo Credentials
Password for all users: Password@123

Government Portal:
- Central Admin: rajesh.kumar@dolr.gov.in
- State Officer: priya.chandran@tn.gov.in
- District Collector: collector.chennai@tn.gov.in
- Field Officer: kumaran.s@tn.gov.in

Landowner Portal:
- Phone: 9840001204, Last 4: 1204
- Phone: 9840001210, Last 4: 1210

## For Full Remote Access (2-Tunnel Method)

If your friend is on a different network and needs full API access:

Terminal 1 - Backend Ngrok:
cd backend
npm start
# In new terminal: ngrok http 5000

Terminal 2 - Update Frontend & Deploy:
cd frontend
# Edit .env.production with backend ngrok URL
npm run build
npm run preview
# In new terminal: ngrok http 5173

See NGROK_SETUP.md for detailed manual steps.
"@

Set-Content -Path ".\NGROK_URLS.txt" -Value $urlsContent
Write-Host "📝 URLs saved to NGROK_URLS.txt" -ForegroundColor Green
Write-Host ""

# Monitor services
Write-Host "🔄 Monitoring services... (Press Ctrl+C to stop)" -ForegroundColor Cyan
Write-Host ""

try {
    while ($true) {
        Start-Sleep -Seconds 30
        
        # Check job status
        if ($backendJob.State -ne "Running") {
            Write-Host "⚠️  Backend stopped" -ForegroundColor Red
        }
        if ($frontendJob.State -ne "Running") {
            Write-Host "⚠️  Frontend stopped" -ForegroundColor Red
        }
        if ($ngrokJob.State -ne "Running") {
            Write-Host "⚠️  Ngrok stopped" -ForegroundColor Red
        }
    }
} finally {
    Write-Host ""
    Write-Host "🛑 Stopping all services..." -ForegroundColor Yellow
    
    Stop-Job $backendJob -ErrorAction SilentlyContinue
    Stop-Job $frontendJob -ErrorAction SilentlyContinue
    Stop-Job $ngrokJob -ErrorAction SilentlyContinue
    
    Remove-Job $backendJob -ErrorAction SilentlyContinue
    Remove-Job $frontendJob -ErrorAction SilentlyContinue
    Remove-Job $ngrokJob -ErrorAction SilentlyContinue
    
    Write-Host "✅ All services stopped" -ForegroundColor Green
    Write-Host ""
}
